Repository ucsb-cs156-w24/proj-courses-w24-5pm-1, pull requests merged in 2024-03, with the labels that each got.

#26 Add link to developer/GH info in Admin dropdown
  .gitignore
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  src/main/resources/application.properties
Labels: 5 points

#28 Added course description to course details page
  frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsIndexPage.test.js
Labels: 10 points

#30 Associated Courses aren't deleted with Schedule
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 20 points

#32 FEATURE: Add sections to personal schedule directly from search
  frontend/src/App.js
  frontend/src/main/components/Courses/CourseForm.js
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/pages/Courses/PSSpecificCoursePage.js
  frontend/src/main/pages/SectionSearches/SectionSearchesIndexPage.js
  frontend/src/stories/components/Sections/SectionTable.stories.js
  frontend/src/tests/components/Courses/CourseForm.test.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
  frontend/src/tests/pages/Courses/SpecificCourseCreatePage.test.js
Labels: 20 points

#31 FEATURE: More descriptive error message on personal schedule and Button!
  frontend/src/main/pages/Courses/PSCourseCreatePage.js
  frontend/src/tests/pages/Courses/CoursesCreatePage.test.js
Labels: 10 points

#33 Add edit page for personal schedules
  frontend/src/fixtures/editCourseFixtures.js
  frontend/src/main/components/PersonalSchedules/PersonalScheduleTableEdit.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/main/utils/PersonalScheduleEditUtils.js
  frontend/src/stories/components/PersonalSchedules/PersonalScheduleEditTable.stories.js
  frontend/src/tests/components/PersonalSchedules/PersonalScheduleTableEdit.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  frontend/src/tests/utils/PersonalScheduleEditUtils.test.js
  src/main/resources/application.properties
Labels: 20 points

#36 FEATURE: More descriptive personal courses page #8
  frontend/src/fixtures/courseWithScheduleFixtures.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/main/pages/Courses/PSCourseIndexPage.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  frontend/src/tests/pages/Courses/CoursesIndexPage.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseDetailsController.java
  src/main/java/edu/ucsb/cs156/courses/models/CourseWithSchedule.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseDetailsControllerTests.java
  src/test/java/edu/ucsb/cs156/courses/documents/CourseWithScheduleFixtures.java
Labels: 10 points
